//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TempSales
    {
        public int ID { get; set; }
        public int ShopingCart_ProductID { get; set; }
        public System.DateTime Date { get; set; }
        public string BankGetNo { get; set; }
        public bool Status { get; set; }
    
        public virtual Tbl_ShopingCart Tbl_ShopingCart { get; set; }
    }
}
