//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_GroupFilters_Categories
    {
        public int ID { get; set; }
        public int TopicID { get; set; }
        public int FilterID { get; set; }
    
        public virtual Tbl_Categoris Tbl_Categoris { get; set; }
        public virtual Tbl_GroupFilters Tbl_GroupFilters { get; set; }
    }
}
