//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Auctions
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public int Price { get; set; }
        public bool Confirm_Price { get; set; }
    
        public virtual Tbl_Products Tbl_Products { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
